# Generated by Django 4.2.16 on 2024-10-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
